development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
<<<<<<< HEAD
  url: redis://h:asdfqwer1234asdf@ec2-111-1-1-1.compute-1.amazonaws.com:111
=======
  url: redis://h:p97f4ddb2aacd4224b4efb3eac4626d36a8f4223fbb0b100f7c6a48c008ca3328@ec2-34-195-166-91.compute-1.amazonaws.com:29559
>>>>>>> ab14cd05dc8baf1f43b6ea3d0c1742b03a206f8e
